# Generated by Django 2.2.6 on 2019-11-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('admin', 'Es Admin'), ('cliente', 'Es Cliente'))},
        ),
    ]
