# Generated by Django 2.2.6 on 2019-11-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0002_auto_20191117_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('admin', 'Es Admin'), ('usuraio', 'Es Usuraio'))},
        ),
    ]
