# Generated by Django 2.2.6 on 2019-11-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0005_auto_20191117_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('usuario2', 'Es User'), ('usuraio', 'Es Usuraio'))},
        ),
    ]
